### ISSUE TITLE
qeastion

### ISSUE THREAD

**Issue by WesleyVanNeck** [StollD/fedora-linux-surface#1]
is this still a thing https://github.com/jakeday/linux-surface/issues/374
 on fedora

**Comment by StollD** [comment]
If the fix isn't in qzeds patchset for 5.2, it won't be in my fedora builds either.

So it most likely would still happen.

**Comment by WesleyVanNeck** [comment]
@StollD it's now in qzed kernel is it now in your kernel

**Comment by StollD** [comment]
As I already said, I'm not cherry picking changes. If it is in qzeds repository, it is in the builds that came after it was added there.

**Comment by WesleyVanNeck** [comment]
@StollD  i think you misenderstand me or i misunderstoed you https://github.com/qzed/linux-surface/commit/d8b26bd3b703d4c71524aad70d90384909fb4bf1 but any it got mergerd in by qzed
so thats why am asking

**Comment by StollD** [comment]
I don't think I misunderstood you. You asked if *some change* is in my fedora kernel builds. I answered, that if it was merged into qzeds patchset, it **will** be in my builds, because I don't change the patches in any way, I just use the latest version of whatever is in qzeds repository.
