### ISSUE TITLE
Fedora 31 - Your repo cannot be added.

### ISSUE THREAD

**Issue by linuxcrash** [StollD/fedora-linux-surface#10]
I always get an 404 error when trying to add your repo on my Surface Go.

`
sudo dnf config-manager --add-repo=https://tmsp.io/fs/repos/fedora/linux-surface/linux-surface.repo
Adding repo from: https://tmsp.io/fs/repos/fedora/linux-surface/linux-surface.repo
Status code: 404 for https://tmsp.io/fs/repos/fedora/linux-surface/linux-surface.repo (IP: 37.120.189.81)
Error: Configuration of repo failed
`

**Comment by StollD** [comment]
The repos are unavailable right now because we are migrating them to a new setup under the linux-surface github organisation. They will soon be available again, under https://pkg.surfacelinux.com

In the meantime, you can download one of the fedora releases from https://github.com/linux-surface/linux-surface - they are marked as tests but the packages should work just fine.

**Comment by linuxcrash** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thanks for the fast reply. I'll try then later. With that the issue can be closed.Thanks.                                                                                                                                             Gesendet über BlackBerry Hub+ Posteingang für Android                                                                                                                                                                           Von: notifications@github.comGesendet: 23. Februar 2020 18:38An: fedora-linux-surface@noreply.github.comAntworten: reply@reply.github.comCc: albin@mrty.ch; author@noreply.github.comBetreff: Re: [StollD/fedora-linux-surface] Fedora 31 - Your repo cannot be added. (#10)  The repos are unavailable right now because we are migrating them to a new setup under the linux-surface github organisation. They will soon be available again, under https://pkg.surfacelinux.com
In the meantime, you can download one of the fedora releases from https://github.com/linux-surface/linux-surface - they are marked as tests but the packages should work just fine.
