### ISSUE TITLE
Keep kernel-surface as default under GRUB

### ISSUE THREAD

**Issue by thebitstick** [StollD/fedora-linux-surface#2]
Is there anyway to do this automatically with dnf?
Anytime I update and there isn't an update for kernel-surface and only the regular kernel, it puts the regular kernel as default and I have to manually set the kernel-surface kernel as default via `grubby`.
With `grubby` it is easier to do, but I'd rather not have to do in it in the first place.

**Comment by StollD** [comment]
There is no straightforward config option to do this as far as I know. You could uninstall the default kernel but that is risky and not recommended.

What I did was using systemd to run `grubby` every time a file under `/boot` gets touched.

* default-kernel.service:
```ini
[Unit]
Description=Fedora default kernel updater

[Service]
Type=oneshot
ExecStart=/bin/sh -c "grubby --set-default /boot/vmlinuz*surface*"
```

* default-kernel.path:
```ini
[Unit]
Description=Fedora default kernel updater

[Path]
PathChanged=/boot

[Install]
WantedBy=default.target
```

**Comment by thebitstick** [comment]
I put both of these under /etc/systemd/system/ and enabled the .path configuration.
I'll just close this since I was looking for this kind of solution (like a dnf hook or system unit).
