### ISSUE TITLE
MOK files are deleted when running build.sh

### ISSUE THREAD

**Issue by thmichel** [StollD/fedora-linux-surface#3]
When trying to compile the kernel using build.sh , all MOK files are deleted in the keys directory when the script runs 
git reset --hard HEAD
Thus the kernel gets not sifned with my certificate. 
Probably the build script should store the files before running the git reset and copy them back afterwards?

**Comment by StollD** [comment]
The files are copied from here after resetting the kernel tree: https://github.com/StollD/fedora-linux-surface/tree/master/files/keys

So it *should* be enough to simply replace my keys in that directory with your own ones.

**Comment by thmichel** [comment]
Sorry, put them into the linux-surface/keys folder. Please close the issue, stupid error on my end.
