### ISSUE TITLE
Libwacom-surface not working properly after fresh install

### ISSUE THREAD

**Issue by alexanderi96** [StollD/fedora-linux-surface#5]
Hi there, this is the second time that i try Fedora on my Surface Pro 2017. Last time I had no problems installing every driver following your guide on Fedora 30.

This time with Fedora 31 I'm not able get the touchscreen libs work properly and the overall system seems to be a little bit laggy compared to the previous version
Do you have any suggestion on how to get the touch screen work again?

Thank you for your support!

**Comment by StollD** [comment]
What do you mean by touchscreen libs exactly? The title mentions libwacom-surface which is only responsible for touchscreen rotation. Does the touchscreen itself work?

You should probably post your dmesg (run `dmesg > dmesg.txt` in a shell, and upload that file). Also, make sure you are on `5.3.8-2` as `5.3.8-1` was a bad build and lacked some important modules.

**Comment by alexanderi96** [comment]
Hi, I surely made a little bit of confusion with the names, my fault.
Anyway, the touchscreen was not working at all. I say "was" because I decided to go back to fedora 30, install the kernel (now I'm on the 5.3.8-2 for sure) and upgrade to 31. This time everything seems to work correctly.
