### ISSUE TITLE
000 wrong password ?

### ISSUE THREAD

**Issue by tv1d** [StollD/fedora-linux-surface#7]
Hi, I'm at the UEFI screen, I select enroll MOK, but when I try the password 000, it says it's invalid ?.

**Comment by StollD** [comment]
The password changed to `surface` some time ago, so that it uses the same one as the packages for Arch and Debian. It should have wrote a small tutorial to the terminal when you installed it. I simply forgot to update the README accordingly, sorry.

**Comment by tv1d** [comment]
thank you, since I skipped the password I get this message when I try to load the kernel: error: ../../grub-core/loader/i386/efi/linux.c:314/vmlinuz...surface  has invalid signature.
../../grub-core/loader/i386/efi/linux you need to load the kernel first..

I reinstalled the kernel but I get the same error, is there any way to get the password prompt again ?

**Comment by CrispyBacon1999** [comment]
Can the readme be updated to match this? I just did the same thing using 000 for the password since that's what the readme shows.

**Comment by StollD** [comment]
Whoops, I somehow was under the impression that I already did that. Updated the README accordingly.
