### ISSUE TITLE
Have no battery indicator.

### ISSUE THREAD

**Issue by CrispyBacon1999** [StollD/fedora-linux-surface#9]
https://github.com/jakeday/linux-surface/pull/321 seems like it fixed an issue that's still coming up. #4 is the same issue, but I'm getting this problem after installing it today. My laptop isn't detecting the battery for acpi. Running on 5.3.16-300.fc31.x86_64.

**Comment by StollD** [comment]
You are running the stock Fedora kernel. Please make sure that `uname -r` contains `surface`.

**Comment by CrispyBacon1999** [comment]
Ended up needing to use `grubby --set-default` to select the kernel since apparently the grub selection I originally made didn't persist between reboots.
